version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WeatherFashion"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16zw4ol4c8176"
s3_prefix = "WeatherFashion"
region = "ap-northeast-1"
profile = "ryo_sasaki"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
