AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  WeatherFashion

Globals:
  Function:
    Timeout: 3

Resources:
  # API Gateway
  WeatherFashionAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
  # Lambda
  WeatherFashionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/dist
      Handler: index.handler
      Runtime: nodejs12.x
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      Events:
        WeatherFashionAPI:
          Type: Api
          Properties:
            RestApiId: !Ref WeatherFashionAPI
            Path: /
            Method: post

Outputs:
  WeatherFashionAPI:
    Description: 'API Gateway'
    Value: !Sub 'https://${WeatherFashionAPI}.execute-api.${AWS::Region}.amazonaws.com/v1'
  WeatherFashionFunction:
    Description: 'Lambda'
    Value: !GetAtt WeatherFashionFunction.Arn
  WeatherFashionFunctionIamRole:
    Description: 'IAM Role'
    Value: !GetAtt WeatherFashionFunctionRole.Arn
